on:
  workflow_dispatch:
    inputs: 
      Npm-package:
        type: string
        default: "Npm package here"
        required: true
    

jobs:
  main:
    name: Install ${{ inputs.Npm-package }} + commit
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: setup
      run: npm install ${{ inputs.Npm-package }} 


    - name: Commit changes
      run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Npm Bot"
          git add .
          git commit -m "Transfer ${{ inputs.Npm-package }} to root"
          git push origin HEAD:main
      
      
