name: Create app and transfer contents

on:
  workflow_dispatch:
    inputs:
      Create-Command:
        type: string
        required: true
        default: create-react-app@latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize Git
        run: |
          if [ ! -d ".git" ]; then
            git init
            echo "Git initialized"
          else
            echo "Git already initialized"
          fi


      - name: Set up Git user
        run: |
          git config --global user.email "@actions@github.com"
          git config --global user.name "Setup Bot"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Create app
        env:
          SKIP_GIT: true
        run: npx ${{ inputs.Create-Command }} wbrtc 

      - name: Transfer Contents to Root (excluding node_modules)
        run: |
          cd wbrtc
          shopt -s dotglob
          find . ! -path "./node_modules" -maxdepth 1 -exec mv {} .. \;
          cd ..
          rm -rf wbrtc

      - name: Commit changes
        run: |
          git add .
          git commit -m "Transfer Next.js app contents to root"
          git push origin HEAD:main
